### ISSUE TITLE
Commentaire avec apostrophe empêche l'enregistrement

### ISSUE THREAD

**Issue by eiffagemetaldebug** [eiffagemetal/Beta-Pointage#10]
Je remplis le formulaire avec une modif interne, il s'affiche bien dans la liste, mais au moment de l'enregistrement, la ligne disparaît !

Maxime

**Comment by eiffagemetalmarco** [comment]
c'est vraiment étrange je viens de le faire de mon côté et j'ai aucun soucis. Tu as essayé plusieurs fois ?

**Comment by eiffagemetaldebug** [comment]
OK, j'ai compris : il plante à cause du commentaire en fait dans lequel je mets une apostrophe !!!

**Comment by eiffagemetalmarco** [comment]
effectivement je vais corriger çà. merci

**Comment by eiffagemetalmarco** [comment]
c'est corrigé
