### ISSUE TITLE
Problème compatibilité jour férié - jour travaillé - Martin

### ISSUE THREAD

**Issue by eiffagemetaldebug** [eiffagemetal/Beta-Pointage#5]
![imprime ecran - feuille de pointage](https://cloud.githubusercontent.com/assets/23312642/20062376/c72af1ea-a503-11e6-8685-a21571dc4a0d.png)

Tu peux allouer moins de 7.4 heures aux jours férié du coup tu peux avoir su rle même jour 3.7 heures de jour férié et 3.7 heures de travail sur un projet. Il faudrait bloquer à 7.4 comme les congés.

**Comment by eiffagemetalmarco** [comment]
c'est corrigé
merci
