### ISSUE TITLE
Pointage sur section indisponible

### ISSUE THREAD

**Issue by eiffagemetaldebug** [eiffagemetal/Beta-Pointage#6]
Ajouter 9300 - Frais généraux en codes analytiques, et le pointage sur section (dans Hors Projet du coup ?)

Maxime

**Comment by eiffagemetaldebug** [comment]
c'est fait

merci

**Comment by eiffagemetaldebug** [comment]
Presque, car il manque la section BE000500 (générale), la 506 (BE Vélizy) et la 502 est en doublon !

**Comment by eiffagemetalmarco** [comment]
cette fois ci çà devrait être bon

**Comment by eiffagemetaldebug** [comment]
Une vérif qu'il faut faire : on ne peut pointer sur section qu'avec un code 9300. Là j'ai réussi à pointer avec 1300 - étude electrique.

**Comment by eiffagemetalmarco** [comment]
c'est corrigé
