### ISSUE TITLE
Disparition de certains pointages ?

### ISSUE THREAD

**Issue by eiffagemetaldebug** [eiffagemetal/Beta-Pointage#8]
Je ne suis pas certain que le problème ne vient pas de moi, mais je suis quand même presque sûr d'avoir fait - et enregistré, sans soumettre - deux lignes de pointages pour hier, qui ont disparu aujourd'hui...

J'ai refait la même manip et après déconnexion et reconnexion les ligens sont bien toujours là... A moins qu'il n'y ait possiblement un souci quand on change de jour ? Je vérifierai demain.

Quoi qu'il en soit, je pense que quitter la page sans avoir enregistré peut être rapidement frustrant pour l'utilisateur qui ne le ferait pas exprès. Du coup un message d'avertissement du type "attention vous allez quitter la page avec des données non sauvegardées" peut être intéressant ?

**Comment by eiffagemetalmarco** [comment]
Pour ce qui est du message d'avertissement c'est en effet une bonne idée, je vais essayer de le mettre en place. 

 Pour ce qui est de ton problème de pointage j'aurais besoin de ton nom pour vérifier si un problème est survenu dans la base de données.

Merci

**Comment by eiffagemetaldebug** [comment]
Maxime !
On aurait du utiliser un compte par personne...

**Comment by eiffagemetalmarco** [comment]
le problème d'utiliser un compte par personne c'est qu' au delà de 5 ça devient payant github...

**Comment by eiffagemetalmarco** [comment]
concernant tes pointages disparus je ne vois rien d’anormal. Tiens moi au courant si tu rencontre le même bug demain mais normalement il n'y a pas de raison

**Comment by eiffagemetaldebug** [comment]
Mes pointages sont toujours là. J'avais donc bien fait une fausse manip.
