### ISSUE TITLE
Classement chronologique des pointages

### ISSUE THREAD

**Issue by eiffagemetaldebug** [eiffagemetal/Beta-Pointage#9]
![capture](https://cloud.githubusercontent.com/assets/23312642/20133615/8bced8c6-a668-11e6-9cf7-13b71f1b117f.JPG)

J'ai pointé le lundi puis le mardi puis le lundi. Ca ne serait pas plus logique que le lundi aille avec le lundi ?

(remarque, s'il y a des pointages pour plusieurs jours, ça ne va pas marcher. Il y a un peu de recherche à faire sur ce sujet pour améliorer le visuel)

**Comment by eiffagemetalmarco** [comment]
les pointages sont maintenant automatiquement classés par ordre chronologique
